import 'regenerator-runtime'

import ChatProvider from '@/provider/chat-provider'
import { Web3Modal } from '@/provider/ethereum-provider'
import SolanaProvider from '@/provider/solana-provider'
import SuiProvider from '@/provider/sui-provider'
import WrapperProvider from '@/provider/wrapper-provider'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_HOST || 'https://artify.vertiree.com/'),
  title: 'Artify',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  openGraph: {
    title: 'Artify',
    description: `Hello, I'm Artify. I can assist you in creating NFTs from any topic using your voice. Please tell me the theme you'd like to create today!`,
    url: process.env.NEXT_PUBLIC_APP_HOST || 'https://artify.vertiree.com/',
    type: 'website',
    images: [
      {
        url: '/images/thumbnail.png',
        width: 800,
        height: 600,
      },
    ],
  },
}
export const viewport: Viewport = {
  themeColor: '#FFFFFF',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  width: '100%',
  userScalable: false,
  viewportFit: 'cover',
}

// export const metadata: Metadata = {
//   title: 'Artify',
//   description: 'Generated by create next app',
//   openGraph: {
//     title: 'Artify',
//     description: `Hello, I'm Artify. I can assist you in creating NFTs from any topic using your voice. Please tell me the theme you'd like to create today!`,
//     type: 'website',
//     images: [
//       {
//         url: '/images/thumbnail.png',
//         width: 800,
//         height: 600,
//       },
//     ],
//   },
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SolanaProvider>
          <SuiProvider>
            <Web3Modal>
              <WrapperProvider>
                <ChatProvider>{children}</ChatProvider>
              </WrapperProvider>
            </Web3Modal>
          </SuiProvider>
        </SolanaProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
