import {
  arbitrum,
  arbitrumGoerli,
  avalanche,
  avalancheFuji,
  base,
  baseGoerli,
  baseSepolia,
  bsc,
  bscTestnet,
  celo,
  celoAlfajores,
  celoCannoli,
  fantom,
  fantomTestnet,
  filecoin,
  filecoinCalibration,
  filecoinHyperspace,
  goerli,
  linea,
  lineaTestnet,
  mantle,
  mantleTestnet,
  moonbaseAlpha,
  moonbeam,
  optimism,
  optimismGoerli,
  optimismSepolia,
  polygon,
  polygonMumbai,
  scroll,
  scrollSepolia,
  scrollTestnet,
} from 'viem/chains'
import { mainnet, sepolia } from 'wagmi'

const configChains = [
  mainnet,
  goerli,
  sepolia,
  arbitrum,
  arbitrumGoerli,
  optimism,
  optimismGoerli,
  optimismSepolia,
  linea,
  lineaTestnet,
  base,
  baseGoerli,
  baseSepolia,
  avalanche,
  avalancheFuji,
  polygon,
  polygonMumbai,
  bsc,
  bscTestnet,
  fantom,
  fantomTestnet,
  moonbeam,
  moonbaseAlpha,
  mantle,
  mantleTestnet,
  scroll,
  scrollTestnet,
  scrollSepolia,
  celo,
  celoAlfajores,
  celoCannoli,
  filecoin,
  filecoinCalibration,
  filecoinHyperspace,
]

export { configChains }
